# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-27 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.FileField(default=1, upload_to=b''),
            preserve_default=False,
        ),
    ]
