# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-05 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to=b'uploads'),
        ),
    ]
