# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160705_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=b'uploads'),
        ),
    ]
